name: Cron

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo $(date) > hogehoge.txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update hogehoge.txt
          branch: ci/update_text
          branch-suffix: timestamp
