name: Cron

on:
  schedule:
    - cron: "22 23 * * *"
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Hello
        run: |
          echo "Hello, GitHub Actions"
