name: Run Test
on:
  push:
  workflow_dispatch:
    inputs:
      qa_env:
        description: '接続するAPIのqa環境を指定する'
        required: true
        type: choice
        options:
          - qa1
          - qa2
          - qa3
          - qa4
          - qa5
          - qa6
          - qa7

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compare version
        run: |
          ANDROID_APP_VERSION=$(sed -n 's/.*versionName "\(.*\)".*/\1/p' app/build.gradle)
          IOS_APP_VERSION=$(sed -n 's/.*app_version "\(.*\)".*/\1/p' ios/fastlane/Deliverfile)
          APP_VERSION = ruby -e "v1 = Gem::Version.new('$ANDROID_APP_VERSION'); v2 = Gem::Version.new('$IOS_APP_VERSION'); puts v1 > v2 ? v1 : v2"
          echo "APP_VERSION=$APP_VERSION"
      - name: Hoge
        run: |
          sed -i -e 's/\(.*app_version \)"\(.*\)"/\1"9.0.0"/' ios/fastlane/Deliverfile
          cat ios/fastlane/Deliverfile
          
