name: Hello, World!
on: push

jobs:
  build:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: mkdir -p /home/runner/.android && touch /home/runner/.android/repositories.cfg
      - run: chmod 755 /usr/local/lib/android/sdk
      - run: ./gradlew testDebugUnitTest
