name: Run Test
on:
  push:
  workflow_dispatch:
    inputs:
      qa_env:
        description: '接続するAPIのqa環境を指定する'
        required: true
        type: choice
        options:
          - qa1
          - qa2
          - qa3
          - qa4
          - qa5
          - qa6
          - qa7

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: compare-versions
        name: Compare versions
        run: |
          android_app_version=$(sed -n 's/.*versionName "\(.*\)".*/\1/p' android/app/build.gradle)
          ios_app_version=$(sed -n 's/.*app_version "\(.*\)".*/\1/p' ios/fastlane/Deliverfile)
          app_version=$(ruby -e "v1 = Gem::Version.new('$android_app_version'); v2 = Gem::Version.new('$ios_app_version'); puts v1 > v2 ? v1 : v2")
          echo "app_version=$app_version" >> "$GITHUB_OUTPUT"
      - name: Hoge
        run: |
          echo "app_version: ${{ steps.compare-versions.outputs.app_version }}"
          sed -i -e 's/\(.*app_version \)"\(.*\)"/\1"9.0.0"/' ios/fastlane/Deliverfile
          cat ios/fastlane/Deliverfile
          
