name: Run Test
on:
  push:
  workflow_dispatch:
    inputs:
      qa_env:
        description: '接続するAPIのqa環境を指定する'
        required: true
        type: choice
        options:
          - qa1
          - qa2
          - qa3
          - qa4
          - qa5
          - qa6
          - qa7

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hoge
        run: |
          sed -i -e 's/\(.*app_version \)"\(.*\)"/\1"9.0.0"/' ios/fastlane/Deliverfile
          cat ios/fastlane/Deliverfile
          
