name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      qa_env:
        description: '接続するAPIのqa環境を指定する'
        required: true
        type: choice
        options:
          - qa1
          - qa2
          - qa3
          - qa4
          - qa5
          - qa6
          - qa7

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo qa_env
        run: echo "Start deploy to ${{ inputs.qa_env }}"
      - name: echo branch
        run: echo "branch name ${{ inputs.ref_name }}"
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: echo branch2
        run: echo "branch name ${{ steps.extract_branch.outputs.branch }}"
